language: python
python:
  - "3.6"


# command to run tests
script:
  - python pybuild.py 
deploy:
  provider: submissions
  api_key: "GITHUB OAUTH TOKEN"
  file: "map.json"
  skip_cleanup: true
  on:
    tags: true
