language: python
python:
- '3.6'
script:
- python pybuild.py

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN  
  file: "map.json"
  keep-history: true
  on:
    branch: master