language: python
python:
  - "3.6"

# command to install dependencies
install:
  - pip install -r requirements.txt
# command to run tests
script:
  - pybuild 
deploy:
  provider: releases
  api_key: "GITHUB OAUTH TOKEN"
  file: "map.json"
  skip_cleanup: true
  on:
    tags: true
